### PR TITLE
Fix 'PIF.get_primary_address' in IPv6

### PR DESCRIPTION
**Pull request by benjamreis**
[Koji build scratch v8.3-incoming](https://koji.xcp-ng.org/taskinfo?taskID=47168)

### CODE REVIEW

**Comment by stormi** [comment]
This PR will need to be rebased, as we merged another which had higher priority. I'd also wait for the upstream PR to be finalized (at least in our view: we don't want to remain blocked for long) before merging.

**Comment by benjamreis** [comment]
from XCP-ng 8.3 it's fixed, if the code changes we'll get it with new sources.

**Comment by stormi** [comment]
> from XCP-ng 8.3 it's fixed, if the code changes we'll get it with new sources.

There are many unadressed comments in the upstream PR. I don't think we should rush the merge to XCP-ng 8.3 until they are addressed, just to publish the build a few days earlier.

**Comment by stormi** [comment]
We'll merge as is, as it looks good functionnally, and keep working on a better implementation upstream.

**Review by stormi — APPROVED** [review]

**Comment by stormi** [comment]
Koji build (v8.3-incoming): http://koji.xcp-ng.org/taskinfo?taskID=47485

**Pull request merged**
