### PR TITLE
dont generate link local

### PR DESCRIPTION
**Pull request by gthvn1**

### CODE REVIEW

**Comment by gthvn1** [comment]
Put it as a draft until update to v24.14.0 is merged.

**Review by benjamreis — APPROVED** [review]

**Comment by stormi** [comment]
You can now rebase

**Comment by gthvn1** [comment]
- Rebased
- build scratch: http://koji.xcp-ng.org/taskinfo?taskID=57982

**Review by stormi — APPROVED** [review]

**Comment by stormi** [comment]
Koji build to v8.3-incoming: http://koji.xcp-ng.org/taskinfo?taskID=58068

**Pull request merged**
