### PR TITLE
Only count tested SRs for leaked VDIs

### PR DESCRIPTION
**Pull request by benjamreis**
See: https://github.com/xapi-project/xen-api/pull/5189

### CODE REVIEW

**Comment by benjamreis** [comment]
[v8.2-incoming scratch build](https://koji.xcp-ng.org/taskinfo?taskID=61610)

**Review by gduperrey — APPROVED** [review]

**Comment by stormi** [comment]
What's the context?

**Comment by gduperrey** [comment]
We have a lot of instabilities in the ci for the jobs storage-quicktest.
So I asked Benji about it, and it's something corrected in 8.3, but never bacported in 8.2. Here's something to backport that in 8.2 and to have more stabilities on those tests.

**Review by stormi — APPROVED** [review]

**Comment by benjamreis** [comment]
[v8.2-incoming build](https://koji.xcp-ng.org/taskinfo?taskID=61634)

**Pull request merged**
